contact_links:
  - name: 📢 Feedback
    url: https://step.ci/feedback
    about: Leave your feedback
  - name: 👋 Discord Community
    url: https://discord.gg/KqJJzJ3BTu
    about: Chat, updates and gatherings
  - name: 🙋 GitHub Discussions
    url: https://github.com/stepci/stepci/discussions
    about: Ask and answer questions here
