name: 📢 Feedback
description: Leave your feedback on https://step.ci/feedback
title: "[Feedback]: "
labels: ["feedback"]
body:
  - type: markdown
    attributes:
      value: |
        ## Feedback
        Hey, this is just a placeholder issue template. Please leave your feedback on https://step.ci/feedback
        
        Thank you!
